# This is the YAML config file to make this a little more abstractish

# Stuff about you.
user_config:
  # Your Name. This will be used for the page title
  name: 'Sian Cao'

  # The file you want to parse to be your resume
  # Must be a format supported by github-markup
  file: 'resume.md'
  file-zh: 'resume-zh.md'
  
  # A picture of you. Should be a complete url
  pic: 'http://www.gravatar.com/avatar/5965dd93d497bef6e9a0b4029b0e023d'

  # The google analytics key you wish to use.
  gkey: 'UA-40340886-1'

# For github pages to work, this needs to be the GitHub repository this file is
# stored in.
github:
  remote: 'git@github.com:sonald/Resume.git'
